Traceback (most recent call last):
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\fwilden\AppData\Local\miniconda3\envs\jupyterbook\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
print("Progress:")
score = len(df[(df['Visited']) & (df['Outside EEG'] != True)]) / len(df)
displays = int(score * 40)
print(f"Total: {" " * (20 - len("Total"))}[{"+" * displays}{"." * (40 - displays)}] {len(df[(df['Visited']) & (df["Outside EEG"] != True)])} out of {len(df[df['Outside EEG'] != True])}\n")
for abbr, country in zip(['nld', 'fra', 'ita', 'bel', 'deu', 'lux'], ["Netherlands", "France", "Italy", "Belgium", "Germany", "Luxembourg"]):
    score = len(df[(df['Visited']) & (df['udnp_code'].str.contains(abbr))]) / len(df[df['udnp_code'].str.contains(abbr)])
    displays = int(score * 40)
    symbol = "â‹†" if score == 1 else "+"
    print(f"{country}: {" " * (20 - len(country))}[{symbol * displays}{"." * (40 - displays)}] {len(df[(df['Visited']) & (df['udnp_code'].str.contains(abbr))])} out of {len(df[df['udnp_code'].str.contains(abbr)])}")

print("\nNote: due to transboundary sites the sum of all countries might not match the total")
------------------


[1;36m  Cell [1;32mIn[3], line 4[1;36m[0m
[1;33m    print(f"Total: {" " * (20 - len("Total"))}[{"+" * displays}{"." * (40 - displays)}] {len(df[(df['Visited']) & (df["Outside EEG"] != True)])} out of {len(df[df['Outside EEG'] != True])}\n")[0m
[1;37m                                     ^[0m
[1;31mSyntaxError[0m[1;31m:[0m f-string: expecting '}'


